### ISSUE TITLE
Upgrade to flask 2.X ?

### ISSUE THREAD

**Issue by bfleisch** [isee4xai/iSeeBackend#2]
Hi

Would it be possible to use flask 2.X instead of flask 1.x (which I believe is no longer supported) ?

Flask 1.X seems to create some build issues with jinja2 - see https://github.com/pallets/flask/issues/4494 for more details about it

Error log when launching the app:

```
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from flask import Flask, send_from_directory,request, json, jsonify
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
```

thanks!
Bruno

**Comment by OscarCal** [comment]
Hi
All done, I update to Flask 2.0.3 and no changes where needed in to Python fiels. I already changed the requirements.txt files in both folders.
Thanks for your work!
